# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


pool:
  vmImage: ubuntu-latest


steps:
  - task: CMake@1
    displayName: 'CMake ..'
    inputs:
      cmakeArgs: '..'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'

  - task: CMake@1
    displayName: 'CMake --build . --config Debug'
    inputs:
      cmakeArgs: '--build . --config Debug'

  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: current
      downloadType: single
      artifactName: "UbuntuRelBuild"
      downloadPath: C:/vs projects/test_cmake_2/artifacts